// src/lib/constants.ts
// Central constants and enums for SchoolFin

import { Decimal } from "decimal.js";

export const USER_ROLES = ["PARENT", "BURSAR", "ACCOUNTANT", "PROPRIETOR"] as const;
export type UserRole = (typeof USER_ROLES)[number];

export const SCHOOL_CLASSES = [
  "Playgroup",
  "KG 1",
  "KG 2",
  "Nursery 1",
  "Nursery 2",
  "Primary 1",
  "Primary 2",
  "Primary 3",
  "Primary 4",
  "Primary 5",
  "Primary 6",
  "JSS 1",
  "JSS 2",
  "JSS 3",
  "SSS 1",
  "SSS 2",
  "SSS 3",
] as const;

export type SchoolClass = (typeof SCHOOL_CLASSES)[number];

export const ROLE_DASHBOARDS: Record<UserRole, string> = {
  PARENT: "/parent/dashboard",
  BURSAR: "/bursar/dashboard",
  ACCOUNTANT: "/accountant/dashboard",
  PROPRIETOR: "/proprietor/dashboard",
} as const;

export const AUDIT_ACTIONS = {
  // Authentication & Users
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PARENT_INVITE_SENT: "PARENT_INVITE_SENT",
  PARENT_INVITE_ACCEPTED: "PARENT_INVITE_ACCEPTED",
  PARENT_STUDENT_LINKED: "PARENT_STUDENT_LINKED",
  PARENT_STUDENT_UNLINKED: "PARENT_STUDENT_UNLINKED",

  // Students
  STUDENT_CREATED: "STUDENT_CREATED",
  STUDENT_UPDATED: "STUDENT_UPDATED",
  STUDENT_DEACTIVATED: "STUDENT_DEACTIVATED",
  STUDENT_REACTIVATED: "STUDENT_REACTIVATED",
  STUDENT_DELETED: "STUDENT_DELETED",

  // Academic Terms
  TERM_CREATED: "TERM_CREATED",
  TERM_SET_ACTIVE: "TERM_SET_ACTIVE",
  TERM_UPDATED: "TERM_UPDATED",
  TERM_DELETED: "TERM_DELETED",

  // Fee Structures & Postings
  FEE_STRUCTURE_CREATED: "FEE_STRUCTURE_CREATED",
  FEE_STRUCTURE_UPDATED: "FEE_STRUCTURE_UPDATED",
  FEE_STRUCTURE_DEACTIVATED: "FEE_STRUCTURE_DEACTIVATED",
  FEE_STRUCTURE_DELETED: "FEE_STRUCTURE_DELETED",
  FEE_POSTED_INDIVIDUAL: "FEE_POSTED_INDIVIDUAL",
  FEE_POSTED_BULK: "FEE_POSTED_BULK",
  FEE_POSTING_REVERSED: "FEE_POSTING_REVERSED",

  // Payments & Credits
  MANUAL_CREDIT_CREATED: "MANUAL_CREDIT_CREATED",
  OVERPAYMENT_OVERRIDE: "OVERPAYMENT_OVERRIDE",
  DUPLICATE_PAYMENT_CONFIRMED: "DUPLICATE_PAYMENT_CONFIRMED",
  CREDIT_BALANCE_APPLIED: "CREDIT_BALANCE_APPLIED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  FEE_WAIVER_APPLIED: "FEE_WAIVER_APPLIED",

  // Installments
  INSTALLMENT_PLAN_CREATED: "INSTALLMENT_PLAN_CREATED",
  INSTALLMENT_PLAN_SELECTED: "INSTALLMENT_PLAN_SELECTED",
  INSTALLMENT_CHARGE_FAILED: "INSTALLMENT_CHARGE_FAILED",
  INSTALLMENT_FLAGGED: "INSTALLMENT_FLAGGED",

  // Webhooks
  WEBHOOK_RECEIVED: "WEBHOOK_RECEIVED",
  WEBHOOK_DUPLICATE_DISCARDED: "WEBHOOK_DUPLICATE_DISCARDED",

  // Automation & Debt Collection
  AUTOMATED_MESSAGES_PAUSED: "AUTOMATED_MESSAGES_PAUSED",
  AUTOMATED_MESSAGES_RESUMED: "AUTOMATED_MESSAGES_RESUMED",
  DEBT_SCAN_FAILED: "DEBT_SCAN_FAILED",
  DEBT_COLLECTION_RULE_CREATED: "DEBT_COLLECTION_RULE_CREATED",
  COMMUNICATION_TEMPLATE_CREATED: "COMMUNICATION_TEMPLATE_CREATED",
  BULK_REMINDER_SENT: "BULK_REMINDER_SENT",
  TAX_EXPORT_ASYNC_COMPLETED: "TAX_EXPORT_ASYNC_COMPLETED",
  JOB_FINAL_FAILURE: "JOB_FINAL_FAILURE",
  SMS_CAP_REACHED: "SMS_CAP_REACHED",

  // Compliance & NDPA
  PII_ANONYMISED: "PII_ANONYMISED",
  PII_ACCESSED: "PII_ACCESSED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const SENSITIVE_AUDIT_ACTIONS = new Set<AuditAction>([
  AUDIT_ACTIONS.MANUAL_CREDIT_CREATED,
  AUDIT_ACTIONS.PAYMENT_REFUNDED,
  AUDIT_ACTIONS.USER_ROLE_CHANGED,
  AUDIT_ACTIONS.FEE_WAIVER_APPLIED,
  AUDIT_ACTIONS.OVERPAYMENT_OVERRIDE,
  AUDIT_ACTIONS.DUPLICATE_PAYMENT_CONFIRMED,
  AUDIT_ACTIONS.PII_ANONYMISED,
  AUDIT_ACTIONS.TERM_DELETED,
  AUDIT_ACTIONS.STUDENT_DELETED,
]);

export const OVERPAYMENT_WARNING_THRESHOLD_NGN = new Decimal("5000");

export const SYSTEM_USER_ID = "system";
